Fix get_starred_packages
amano41/apm-sync pull request #1
Opened 2019-11-23 11:34 UTC by kokorinosoba

Fixed bug due to change of output format of "apm starred"

2019-11-25 07:06 UTC, amano41 requested changes
Package names are printed in the third column only when the platform is darwin.
https://github.com/atom/apm/blob/master/src/stars.coffee#L80

Could you please add some codes to verify the platform?

2019-11-25 23:41 UTC, kokorinosoba commented
Thanks for telling me. I didn't know that.
I changed the script to get the third column when using OSX.
But I couldn't check the operation with other os.

2019-11-27 06:27 UTC, amano41 requested changes
I tested your code and found some bugs.
Please check the comments below.
Thank you.

2019-11-27 06:27 UTC, amano41 commented on apm-sync.sh
> +	if [ "$(uname | lower)" == 'darwin' ]; then
I suppose 'lower' is your custom command.
Please use 'tr' for instance to ensure the portability.

```suggestion
	if [ "$(uname | tr '[:upper:]' '[:lower:]')" == 'darwin' ]; then
```

You can also just compare with a non-lowercased string (i.e., 'Darwin').

```suggestion
	if [ "$(uname)" == "Darwin" ]; then
```

2019-11-27 06:27 UTC, amano41 commented on apm-sync.sh
> +		exit 0
The exit statement terminates the entire script with the specified exit code.
You should use the return statement in shell functions instead.

2019-11-27 06:27 UTC, amano41 commented on apm-sync.sh
> +		exit 1
same as above

2019-11-27 06:27 UTC, amano41 commented on apm-sync.sh
> +	if [ is_darwin ]; then
No need to use '[ ]' when checking an exit status of a command/function.
In fact, the '[' (test command) in this case will always return true irrespective of the platform.

```suggestion
	if is_darwin; then
```

2019-11-27 06:29 UTC, amano41 commented
Thank you for your effort and cooperation.

There seem to be some bugs.
I'd appreciate if you could fix them.
Then could you squash commits if it is possible?

2019-11-27 07:18 UTC, kokorinosoba commented
Thank you for reviewing my script!
Fixed everything you pointed out :-)

2019-11-27 09:08 UTC, merged

2019-11-27 09:09 UTC, amano41 commented
Thank you for your quick response.
Now this script runs correctly even on the mac. Yay!